### PR TITLE
Fix/hitting character limit when adding <iframe/>

### LINKED ISSUE #994: [Bug] Unable to add iFrame videos due to character limit
### Problem

Since HTML code regarding iframe is part of the 400 character limit (see image below), this does not allow certain agencies to add in iframe. Currently, the workaround is to manually adding the code directly to the back end. 

Screenshot 2022-07-27 at 10 24 59 AM

### Proposed Solution 

Using a regex pattern to get instances of `<iframe></iframe>`, and then not including this subset of the sting as part of the total character count allowed.

### PR DESCRIPTION
**Pull request by kishore03109**
## Problem 

Since HTML code regarding iframe is part of the 400 character limit (see image below), this does not allow certain agencies to add in iframe. Currently, the workaround is to manually adding the code directly to the back end.

Closes #994

## Solution

Using a regex pattern to get instances of `<iframe></iframe>` and `<div></div>` (what our current users are using), and then not including this subset of the sting as part of the total character count allowed.

Note: This is meant to be a temporary workaround, once we move to block editing, this should not be an issue

### CODE REVIEW

File: src/utils/validators.js [hunk 1]
```diff
@@ -560,7 +562,7 @@ const validateContactType = (contactType, value) => {
       break
     }
     case "other": {
-      if (value.length > CONTACT_DESCRIPTION_MAX_LENGTH) {
+      if (getLengthWithoutTags(value) > CONTACT_DESCRIPTION_MAX_LENGTH) {
         errorMessage = `Description should be shorter than ${CONTACT_DESCRIPTION_MAX_LENGTH} characters.`
```
Comment (alexanderleegs) [inline src/utils/validators.js:566]: I think we shouldn't be allowing iframe inside the contact us page - we can leave these as the original restriction

File: src/utils/validators.js [hunk 2]
```diff
@@ -640,7 +642,9 @@ const validateLocationType = (locationType, value) => {
       break
     }
     case "description": {
-      if (value.length > LOCATION_OPERATING_DESCRIPTION_MAX_LENGTH) {
+      if (
+        getLengthWithoutTags(value) > LOCATION_OPERATING_DESCRIPTION_MAX_LENGTH
+      ) {
```
Comment (alexanderleegs) [inline src/utils/validators.js:647]: See above!

File: src/utils/allowedHTML.ts [hunk 3]
```diff
@@ -0,0 +1,21 @@
+/**
+ * Defines the list of allowed HTML tags that do not count towards the total
+ * character limit.
+ *
+ */
+const regrexTests = [
+  new RegExp("(<iframe.*/iframe>)", "gm"),
+  new RegExp("(<div.*/div>)", "gm"),
+]
```
Comment (alexanderleegs) [inline src/utils/allowedHTML.ts:9]: Hmm why do we also allow div tags to bypass the check? This feels like it might be easily abusable to get abnormally long lines

Comment (alexanderleegs) [reply src/utils/allowedHTML.ts:9]: Also nit: `regexTests`!

File: src/utils/allowedHTML.ts [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+/**
+ * @param text raw text input by user
+ * @returns the character length after removing specifc HTML tags
+ */
+export const getLengthWithoutTags = (text: string): number => {
+  let finalText = text
+  for (const regrexTest of regrexTests) {
+    finalText = finalText.replace(regrexTest, "")
+  }
+  return finalText.length
```
Comment (seaerchin) [inline src/utils/allowedHTML.ts:20]: hmm, we might want to express this as a `reduce` operation if it's cleaner but i'll leave it up to you!

File: src/utils/allowedHTML.ts [hunk 5]
```diff
@@ -0,0 +1,21 @@
+/**
+ * Defines the list of allowed HTML tags that do not count towards the total
+ * character limit.
+ *
+ */
+const regrexTests = [
+  new RegExp("(<iframe.*/iframe>)", "gm"),
+  new RegExp("(<div.*/div>)", "gm"),
```
Comment (seaerchin) [inline src/utils/allowedHTML.ts:8]: could i ask why the regexp is not `<iframe>.*</iframe>` (technically still the same but a lil clearer) and why we are including the parenthesis in the regexp?

Comment (kishore03109) [reply src/utils/allowedHTML.ts:8]: Sure, it was to allow for attributes for the <iframe> element. Eg. <iframe src="abc.xyz"></iframe> will not be matched!

File: src/utils/validators.js (hunk 1 above)
Comment (kishore03109) [reply src/utils/validators.js]: makes sense - have made the change!

File: src/utils/allowedHTML.ts (hunk 3 above)
Comment (kishore03109) [reply src/utils/allowedHTML.ts]: hmm I only added it since our users used a `div` to make align their `iframe` - but I agree that this is easily abusable, made the change likewise

File: src/utils/allowedHTML.ts (hunk 5 above)
Comment (seaerchin) [reply src/utils/allowedHTML.ts]: would `<iframe .*>.*</iframe>` be clearer here?

File: src/utils/allowedHTML.ts [hunk 6]
```diff
@@ -0,0 +1,17 @@
...
+/**
+ * @param text raw text input by user
+ * @returns the character length after removing specifc HTML tags
+ */
+export const getLengthWithoutTags = (text: string): number => {
+  let finalText = text
+
+  finalText = finalText.replace(IFRAME_TAG_REGEX, "")
+
+  return finalText.length
```
Comment (seaerchin) [inline src/utils/allowedHTML.ts:16]:
```suggestion
 return text.replace(IFRAME_TAG_REGEX, "").length
```

**Review by seaerchin — CHANGES_REQUESTED** [review]
minor change for clarity

**Review by seaerchin — APPROVED** [review]
